name: queen_validators
description: validate variables with extensions and pure flutter TextFormFelid
  with qValidator function
version: 0.2.1
homepage: https://github.com/maxzod/queen_validators
repository: https://github.com/maxzod/queen_validators
issue_tracker: https://github.com/maxzod/queen_validators/issues
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  email_validator: ^2.0.0-nullsafety
  meta: ^1.3.0

dev_dependencies:
  lint: ^1.5.3
  test: ^1.16.8
