name: queen_validators
description: queen support for validation in flutter , functions for variables validation , Rules for Forms with ZERO extra widgets
version: 1.0.0-beta
homepage: https://github.com/maxzod/queen_validators
repository: https://github.com/maxzod/queen_validators
issue_tracker: https://github.com/maxzod/queen_validators/issues
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  email_validator: ^2.0.1
  meta: ^1.7.0

dev_dependencies:
  lint:
  test: ^1.16.8
