name: queen_validators
description: validate variables with extensions and pure flutter TextFormFeild
  with qValidator function
version: 0.2.0
homepage: https://github.com/maxzod/queen_validators
repository: https://github.com/maxzod/queen_validators
issue_tracker: https://github.com/maxzod/queen_validators/issues
environment:
  sdk: ">=2.12.0 <3.0.0"
dev_dependencies:
  test: ^1.15.7
  pedantic: ^1.11.0
