name: queen_validators
description: helper functions to make the validaation processs easier for variables and forms
version: 0.2.3
homepage: https://github.com/maxzod/queen_validators
repository: https://github.com/maxzod/queen_validators
issue_tracker: https://github.com/maxzod/queen_validators/issues
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  email_validator: ^2.0.1
  meta: ^1.3.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.8
