name: queen_validators
description:  validate variables , forms and DTO s validation
version: 0.0.1
homepage: https://www.twitter.com/maxzod66
environment:
  sdk: ">=2.7.0 <3.0.0"
# dependencies:
# dev_dependencies:
  # test: 
  