name: queen_validators
description: functions to make the validation processs easier for variables and forms with ZERO extra widgets TextFormFeild
version: 1.0.0-beta
homepage: https://github.com/maxzod/queen_validators
repository: https://github.com/maxzod/queen_validators
issue_tracker: https://github.com/maxzod/queen_validators/issues
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  email_validator: ^2.0.1

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.8
